services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: {base64:KXko2f2Hxg650JRQtEy/lGWnt80zyuKd442NIml7uKw=}
      - key: CLOUDINARY_CLOUD_NAME
        value: {dpb8j0atk}
      - key: CLOUDINARY_API_KEY
        value: {125428377694926}
      - key: CLOUDINARY_API_SECRET
        value: {JkF9YDoHKWQ0TSW6qMu5cK2UXEE}
